--- #ansible playbook to run dockerfile

- hosts: server
  user: ansible
  become: yes

  tasks:
    - name: Build Dockerfile
      command: docker build -t spring-boot:1.0-SNAPSHOT /home/ec2-user/docker/

    - name: Run Docker container
      command: docker run -d -p 8080-8888:8080 spring-boot:1.0-SNAPSHOT

